### ISSUE TITLE
What pages should this site have?

### ISSUE THREAD

**Issue by Explosion-Scratch** [Explosion-Scratch/scratchaddons.github.io#1]
I'm thinking these:
- Home (Tells about the addon and who's involved)
- Contribute (Steps to take if one wants to help)
- Download (Where to find the addon, right now, only GitHub but in the future also the chrome webstore and hopefully Firefox too.)
- Contributors (People who helped with this)

**Comment by YOYITsM3M8** [comment]
how about contributors?ffff

**Comment by Explosion-Scratch** [comment]
Oh yeah. I forgot that :P

**Comment by BoomerScratch** [comment]
There should also be a 'Goodbye' page. (ScratchAddons/ScratchAddons#52)

**Comment by YOYITsM3M8** [comment]
yeah

**Comment by YOYITsM3M8** [comment]
also maybe a index.html

**Comment by BoomerScratch** [comment]
@YOYITsM3M8 @Explosion-Scratch Okay lol I'm gonna try to make a nice index.html :P

**Comment by Explosion-Scratch** [comment]
Okay! I'll take those into consideration. I'm going to make a branch of this and start working.

**Comment by Explosion-Scratch** [comment]
Okay! Initial work done!
