### ISSUE TITLE
Questions about coding (plz hlp)

### ISSUE THREAD

**Issue by Explosion-Scratch** [Explosion-Scratch/scratchaddons.github.io#21]
How to I resize (not crop, but make smaller) an iframe?
How do I make text wrap around images instead of them always being on a new line?
How do I animate the shadow on the header/navbar?
How do I make a thanks for downloading page so that when the user clicks a button it downloads a file and then goes to the thanks for downloading page?

**Comment by Explosion-Scratch** [comment]
How do I make the flip cards flip when you _click_ on them, not when they're hovered over?

Also, all of these questions are regarding the new version of the website, you can fiknd the flip card for world_languages at /world_languages.html

**Comment by GrahamSH-LLK** [comment]
I'll help! 
- Use style="height:blankpx; width:blankpx;"
- 
- 
-
-

**Comment by Explosion-Scratch** [comment]
> I'll help!
> 
> * Use style="height:blankpx; width:blankpx;"

I tried that. It just crops it. =/

**Comment by BoomerScratch** [comment]
@Explosion-Scratch You need to set the `width` and `height` _attributes_, not the CSS styles.

**Comment by Explosion-Scratch** [comment]
Ohhh, like ```<iframe width='100px' height='100px'>``` instead of ```style="width: 100px; height: 100px:"```?
