### ISSUE TITLE
nav updates

### ISSUE THREAD

**Issue by JeffaloBob** [Explosion-Scratch/scratchaddons.github.io#35]
i think it would be better if you please remove the home link, make the logo into a link back home and dont do the whole "youre alredy here" thing

**Comment by GrahamSH-LLK** [comment]
### My Thoughts

- I agree with removing the home link and adding a link to the logo. Possibly we could add ScratchAddons to it also. (In text)
- Something less intrusive would be great. Maybe a little shake and a small popup. Or... we could just not make it clickable. (A pointer, not that little hand)

**Comment by Explosion-Scratch** [comment]
Thanks! The only problem is that I'm not really working on the website anymore. @WorldLanguages said through email that the website would be replaced with one by @Hans5958. I'm still waiting for an update on that. Also, World_Languages bought ScratchAddons.com . (P.S. @WorldLanguages can you give me an update on that? When's this going to be ported?)

**Comment by WorldLanguages** [comment]
Soon (tm)

**Comment by GrahamSH-LLK** [comment]
> Soon (tm)
How soon?™

**Comment by JeffaloBob** [comment]
i think the proper ux is to just reload the page (so basically dont do anything special), atleast thats how almost every site i've seen does it
